name: Build & publish forkdiff github-pages
permissions:
  contents: read
  pages: write
  id-token: write
on:
  workflow_dispatch:
  push:
    branches:
      - seismic

jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1000 # make sure to fetch the old commit we diff against

      - name: Build forkdiff
        uses: "docker://protolambda/forkdiff:0.1.0"
        with:
          args: -repo=/github/workspace -fork=/github/workspace/fork.yaml -out=/github/workspace/index.html

      # TODO(samlaf): this was part of the gh-action I copied from, but doesn't seem necessary...
      # if we are successful in pushing to gh-pages, then just delete these comments

      # - name: Setup Pages
      #   uses: actions/configure-pages@v5

      # - name: Build with Jekyll
      #   uses: actions/jekyll-build-pages@v1
      #   with:
      #     source: ./
      #     destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # This needs to run in the github-pages environment to deploy successfully. For more info see:
  # https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
